### ISSUE TITLE
REST API Key not working for the new NewRelic accounts

### ISSUE THREAD

**Issue by srujithpoondla03** [newrelic/cloudformation-partner-integration#12]
Hi, I was trying to register the "NewRelic::Alerts::NrqlAlert" type in my account and create a CFN stack by following instructions in https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-cloudformation-integration .

I have created a new NewRelicAccount and looks like there are two user data structures now and two API's to create API Keys. One in the NewRelicOne and another in legacy, I have tried using the API Keys from both. 

For the API Key created in NewRelicOne I am seeing : 
`com.newrelic.alerts.nrqlalert.AlertApiException: Failed to create alert condition for policy ID: 1. Error message: 'The API key provided is invalid'`

and for the REST API Key :
`com.newrelic.alerts.nrqlalert.AlertApiException: Failed to create alert condition for policy ID: 1. Error message: 'You do not have privileges to perform this action.'`

I have looked through couple other issues on forums and found that there an ongoing migration to move to NewRelicOne for better API experience and GraphQL APIs Authentication. Are the above issues related to that migration ?

**Comment by MattWhelan** [comment]
Make sure the Policy ID in your CF template is one you have access to. Policy ID 1 is apparently not one of those.

**Comment by srujithpoondla03** [comment]
Thanks @MattWhelan. I was able to create a policy and use it.
